Add coverage to workflow
Signed-off-by: Jordi Gil <jgil@redhat.com>

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -56,4 +56,34 @@ jobs:
         id: ginkgo-tests
         run: |
           make test
+          # go install github.com/onsi/ginkgo/v2/ginkgo@v2.23.4
+          # go tool cover -func=coverage/coverage.out
+          # COVERAGE=$(go tool cover --func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
+          # echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
 
+      - uses: actions/upload-artifact@v4
+        with:
+          name: test-coverage
+          path: coverage/coverage.out
+
+  Coverage:
+    needs: test
+    name: "Test Coverage ${{ needs.test.outputs.coverage }}"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install bc
+        run: sudo apt-get update && sudo apt-get install -y bc
+
+      - name: Check Coverage
+        run: |
+          COVERAGE=${{ needs.test.outputs.coverage }}
+          if [[ -z "$COVERAGE" ]]; then
+            echo "Error: Coverage value is empty!"
+            exit 1
+          fi
+          echo "Coverage status: $COVERAGE"
+          MIN_COVERAGE=${MIN_COVERAGE:-72.9}
+          if (( $(echo "$COVERAGE < $MIN_COVERAGE" | bc -l) )); then …
+            echo "Min coverage failed";
+            exit 1;
+          fi
