Install podman package dependencies before running tests in workflow
Signed-off-by: Jordi Gil <jgil@redhat.com>

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -22,9 +22,64 @@ jobs:
 
       - name: Install libbtrfs-dev ubuntu packages to fix build error
         run: |
-          sudo apt-get install libbtrfs-dev -y
+          sudo apt-get install -y \
+          btrfs-progs \
+          gcc \
+          git \
+          golang-go \
+          go-md2man \
+          iptables \
+          libassuan-dev \
+          libbtrfs-dev \
+          libc6-dev \
+          libdevmapper-dev \
+          libglib2.0-dev \
+          libgpgme-dev \
+          libgpg-error-dev \
+          libprotobuf-dev \
+          libprotobuf-c-dev \
+          libseccomp-dev \
+          libselinux1-dev \
+          libsystemd-dev \
+          make \
+          netavark \
+          passt \
+          pkg-config \
+          runc \
+          uidmap
 
       - name: Run Ginkgo tests with coverage
         id: ginkgo-tests
         run: |
-          make test
+          go install github.com/onsi/ginkgo/v2/ginkgo@v2.23.4
+          ginkgo -r --mod=mod --randomize-all --randomize-suites --fail-on-pending --keep-going --cover --coverprofile=coverage.out --coverpkg=./...
+          go tool cover -func=coverage.out
+          COVERAGE=$(go tool cover --func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
+          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: test-coverage
+          path: coverage.out
+
+  Coverage:
+    needs: test
+    name: "Test Coverage ${{ needs.test.outputs.coverage }}"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install bc
+        run: sudo apt-get update && sudo apt-get install -y bc
+
+      - name: Check Coverage
+        run: |
+          COVERAGE=${{ needs.test.outputs.coverage }}
+          if [[ -z "$COVERAGE" ]]; then
+            echo "Error: Coverage value is empty!"
+            exit 1
+          fi
+          echo "Coverage status: $COVERAGE"
+          MIN_COVERAGE=${MIN_COVERAGE:-73.8}
+          if (( $(echo "$COVERAGE < $MIN_COVERAGE" | bc -l) )); then …
+            echo "Min coverage failed";
+            exit 1;
+          fi
